FROM fedora:42

SHELL ["/bin/bash", "-c"] 

# Prepare
RUN useradd fishi0x01 && \
    echo "fishi0x01 ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER fishi0x01
# required for nix to properly source
ENV USER=fishi0x01

# Checkout
COPY --chown=fishi0x01:fishi0x01 . /code
