---
eagle_ide:
  version: "9.6.2"
  url: "http://trial2.autodesk.com/NET17SWDLD/2017/EGLPRM/ESD/Autodesk_EAGLE_9.6.2_English_Linux_64bit.tar.gz"
  checksum: "sha512:4ef17dfa52b1ee0f5ba68896bc3821616a1b7d1a073a586604271cd7129e29671c480cd324cc5eadc517eb300ca4be6efa69423a306944e36732c2aa34cc59a3"
  lib_files_to_remove:
  - "libxcb-dri2.so.0"
  - "libxcb-dri3.so.0"
  - "libxcb-glx.so.0"
  - "libxcb-present.so.0"
  - "libxcb-sync.so.1"
  - "libxcb-xfixes.so.0"
