---
- name: Check if oh-my-bash is installed
  stat:
    path: "/home/{{ machine_user }}/.oh-my-bash"
  register: ohmybash_stats

- name: Install oh-my-bash
  become: true
  become_user: "{{ machine_user }}"
  script: "files/install.sh"
  when: not ohmybash_stats.stat.exists

- name: Ensure custom theme dir exists
  become: true
  become_user: "{{ machine_user }}"
  file:
    path: "/home/{{ machine_user }}/.oh-my-bash/custom/themes/fishi0x01"
    state: directory
    mode: '0755'

- name: link
  file:
    src: "/home/{{ machine_user }}/.bashrc.fishi0x01.theme.sh"
    dest: "/home/{{ machine_user }}/.oh-my-bash/custom/themes/fishi0x01/fishi0x01.theme.sh"
    owner: "{{ machine_user }}"
    group: "{{ machine_user }}"
    state: link

# TODO: make sure the following is in .bashrc
#if [ -f ~/.bash_aliases ]; then
#    . ~/.bash_aliases
#fi
#
#if [ -f ~/.bash_exports ]; then
#    . ~/.bash_exports
#fi
#
#if [ -f ~/.bash_sources ]; then
#    . ~/.bash_sources
#fi
