---
- name: Check if NVM is already installed
  become: yes
  become_user: "{{ machine_user }}"
  stat:
    path: "~/.nvm"
  register: nvm_stat

# https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh
- name: Install NVM
  become: yes
  become_user: "{{ machine_user }}"
  script: "files/nvm-install.sh"
  when: not nvm_stat.stat.exists
