---
- name: Add vhs gpg key
  ansible.builtin.rpm_key:
    key: https://repo.charm.sh/yum/gpg.key
    fingerprint: ED927B38BE981E53CA09153D03BBF595D4DFD35C
    state: present

- name: Add vhs repo
  ansible.builtin.yum_repository:
    name: vhs
    description: vhs repo
    baseurl: https://repo.charm.sh/yum/
    enabled: true
    gpgcheck: true
    gpgkey: https://repo.charm.sh/yum/gpg.key

- name: Install vhs
  ansible.builtin.dnf:
    name:
    - vhs
    state: present
