---
- name: Check if Eagle IDE is installed
  stat: 
    path: "/opt/eagle-{{ eagle_ide.version }}"
  register: eagle

- name: Download and install Eagle IDE
  block:
    - name: Download Eagle IDE
      get_url:
        url: "{{ eagle_ide.url }}"
        dest: "/tmp/eagle-{{ eagle_ide.version }}.tar.gz"
        checksum: "{{ eagle_ide.checksum }}"
        mode: '0777'

    - name: Ensure Eagle dir exists
      file:
        path: "/opt/eagle-{{ eagle_ide.version }}"
        state: directory
        mode: '0755'

    - name: Unarchive Eagle IDE
      unarchive:
        src: "/tmp/eagle-{{ eagle_ide.version }}.tar.gz"
        dest: "/opt/eagle-{{ eagle_ide.version }}/"
        remote_src: yes
        extra_opts: "--strip-components=1"

    - name: Set permissions
      file:
        dest: "/opt/eagle-{{ eagle_ide.version }}"
        owner: "{{ machine_user }}"
        group: "{{ machine_user }}"
        recurse: true

    - name: Remove libxcb files
      file:
        path: "/opt/eagle-{{ eagle_ide.version }}/lib/{{ item }}"
        state: absent
      with_items: "{{ eagle_ide.lib_files_to_remove }}"
  when: not eagle.stat.exists

- name: Eagle IDE link
  file:
    src: "/opt/eagle-{{ eagle_ide.version }}"
    dest: "/opt/eagle"
    owner: "{{ machine_user }}"
    group: "{{ machine_user }}"
    state: link
