---
- name: distribution specific vars
  include_vars: "{{ ansible_distribution }}{{ ansible_distribution_version }}.yaml"

# https://cloudsmith.io/~balena/repos/etcher/setup/#formats-deb
- name: Add balena-etcher repository key
  apt_key:
    data: "{{ lookup('file', 'files/etcher.pgp.pub') }}"
    state: present

- name: Add balena-etcher repositories
  apt_repository:
    repo: "{{item}}"
    state: present
  loop: "{{balena_etcher_repos}}"

- name: Install balena-etcher
  apt:
    name: "{{balena_etcher_package_name}}"
    update_cache: yes
    force_apt_get: yes
    state: present
