---
- name: Check if is installed
  stat:
    path: "/opt/balena-etcher-{{ balena_etcher.version }}"
  register: balena_etcher_stats

- name: Download and install
  block:
    - name: Ensure dir exists
      file:
        path: "/opt/balena-etcher-{{ balena_etcher.version }}"
        state: directory
        mode: '0755'

    - name: Download
      get_url:
        url: "{{ balena_etcher.url }}"
        dest: "/opt/balena-etcher-{{ balena_etcher.version }}/balena-etcher-{{ balena_etcher.version }}.AppImage"
        checksum: "{{ balena_etcher.checksum }}"
        mode: '0775'

    - name: Set permissions
      file:
        dest: "/opt/balena-etcher-{{ balena_etcher.version }}"
        owner: "{{ machine_user }}"
        group: "{{ machine_user }}"
        recurse: true
  when: not balena_etcher_stats.stat.exists

- name: link
  file:
    src: "/opt/balena-etcher-{{ balena_etcher.version }}"
    dest: "/opt/balena-etcher"
    owner: "{{ machine_user }}"
    group: "{{ machine_user }}"
    state: link
