---
- name: Check if Arduino IDE is installed
  stat:
    path: "/opt/arduino-ide_{{ arduino_ide.version }}_Linux_64bit"
  register: arduino

- name: Download and install Arduino IDE
  block:
    - name: Download Arduino IDE
      get_url:
        url: "https://downloads.arduino.cc/arduino-ide/arduino-ide_{{ arduino_ide.version }}_Linux_64bit.zip"
        dest: "/tmp/arduino-{{ arduino_ide.version }}.tar.xz"
        checksum: "{{ arduino_ide.checksum }}"
        mode: '0777'

    - name: Unarchive Arduino IDE
      unarchive:
        src: "/tmp/arduino-{{ arduino_ide.version }}.tar.xz"
        dest: "/opt/"
        remote_src: true
  when: not arduino.stat.exists

- name: Arduino IDE link
  file:
    src: "/opt/arduino-ide_{{ arduino_ide.version }}_Linux_64bit"
    dest: "/opt/arduino"
    owner: "{{ machine_user }}"
    group: "{{ machine_user }}"
    state: link

# https://github.com/esp8266/source-code-examples/issues/26
- name: Add board access
  user:
    name: "{{ machine_user }}"
    groups: tty,dialout
    append: true
