---
- name: Install apt packages
  apt:
    name: "{{ apt_packages }}"
    force_apt_get: yes
    state: present
    update_cache: yes

- name: Enable snapd
  ansible.builtin.service:
    name: snapd
    enabled: yes

- name: Android anbox
  snap:
    name: anbox
    channel: beta
