---
- name: distribution specific vars
  include_vars: "{{ ansible_distribution }}{{ ansible_distribution_version }}.yaml"

- name: distribution specific install
  include_tasks: "{{ ansible_distribution }}{{ ansible_distribution_version }}.yaml"
