---
- name: Install apt packages
  apt:
    name: "{{ apt_packages }}"
    force_apt_get: yes
    state: present
    update_cache: yes

################
# libssl-dev fix
################
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=733644
- name: Fix missing opensslconf.h
  file:
    path: "/usr/include/openssl/opensslconf.h"
    src: "../x86_64-linux-gnu/openssl/opensslconf.h"
    state: link

#############
# sysctl.conf
#############
- name: Configure inotify limits
  template:
    src: "templates/sysctl.d.inotify.conf"
    dest: "/etc/sysctl.d/10-inotify.conf"
    owner: "root"
    group: "root"
    mode: "644"
  notify: 
    - "reload sysctl"

#########
# SMB
#########
- name: Ensure samba conf dir exists (avoid rpcclient errors)
  file: 
    path: "/etc/samba/"
    state: directory

- name: Ensure samba conf file exists (avoid rpcclient errors)
  file: 
    path: "/etc/samba/smb.conf"
    state: file
