---
- hosts: localhost
  become: true
  roles:
    - role: gpg
      tags: [gpg]
    - role: keybase
      tags: [keybase, not-in-vm]
    - role: ohmybash
      tags: [ohmybash]
    - role: asdf
      tags: [asdf]
    - role: fedora_workstation
      tags: [fedora_workstation]
    - role: fedora_large_packages
      tags: [fedora_large_packages, no-test-in-container]
    - role: vscode
      tags: [vscode]
    - role: docker
      tags: [docker, no-test-in-container]
    - role: virtualbox
      tags: [virtualbox, not-in-vm]
    - role: balena_etcher
      tags: [balena_etcher]
    - role: ttyd
      tags: [ttyd]
    - role: vhs
      tags: [vhs]
    - role: arduino_ide
      tags: [arduino_ide]
