---
- hosts: localhost
  become: true
  roles:
    - role: pre # Run this first to install prerequisits
      tags: [pre]
    - role: gpg
      tags: [gpg]
    - role: keybase
      tags: [keybase, not-in-vm]
    - role: ohmybash
      tags: [ohmybash]
    - role: starship
      tags: [starship, no-test-in-container]
    - role: mise
      tags: [mise]
    - role: fedora_workstation
      tags: [fedora_workstation]
    - role: fedora_large_packages
      tags: [fedora_large_packages, no-test-in-container]
    - role: vim
      tags: [vim]
    - role: fonts
      tags: [fonts]
    - role: nix
      tags: [nix]
    - role: krew
      tags: [krew]
    - role: vscode
      tags: [vscode]
    - role: docker
      tags: [docker, no-test-in-container]
    - role: balena_etcher
      tags: [balena_etcher]
    - role: ttyd
      tags: [ttyd]
    - role: vhs
      tags: [vhs]
    - role: arduino_ide
      tags: [arduino_ide]
    - role: k9s
      tags: [k9s]

