---
# https://code.visualstudio.com/docs/setup/linux
- name: Add microsoft.asc
  ansible.builtin.rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    # gpg --show-keys file.asc
    fingerprint: BC528686B50D79E339D3721CEB3E94ADBE1229CF
    state: present

- name: Add vscode repo
  ansible.builtin.yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: true
    enabled: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc  

- name: Install vscode
  ansible.builtin.dnf:
    name: "code"
    state: present
