---
- name: Check if flutter is installed
  stat: 
    path: "/opt/flutter"
  register: flutter_stats

- name: Install flutter
  block:
    - name: Clone repo
      git:
        repo: "https://github.com/flutter/flutter.git"
        dest: "/opt/flutter"
        version: "{{ flutter.version }}"

    - name: Set permissions
      file:
        dest: "/opt/flutter"
        owner: "{{ machine_user }}"
        group: "{{ machine_user }}"
        recurse: true
  when: not flutter_stats.stat.exists
