---
- name: Check if Openshift Client is installed
  stat:
    path: "/opt/openshift-client-{{ oc.version }}"
  register: openshift_client

- name: Download and install Openshift Client
  block:
    - name: Download Openshift Client
      get_url:
        url: "https://github.com/openshift/okd/releases/download/{{ oc.version }}.okd-2021-12-12-025847/openshift-client-linux-{{ oc.version }}.okd-2021-12-12-025847.tar.gz"
        dest: "/tmp/oc-{{ oc.version }}.tar.gz"
        checksum: "{{ oc.checksum }}"
        mode: '0777'

    - name: Ensure Openshift Client dir exists
      file:
        path: "/opt/oc-{{ oc.version }}"
        state: directory
        mode: '0755'

    - name: Unarchive Openshift Client
      unarchive:
        src: "/tmp/oc-{{ oc.version }}.tar.gz"
        dest: "/opt/oc-{{ oc.version }}/"
        remote_src: true

    - name: Bash completion
      shell: "/opt/oc-{{ oc.version }}/oc completion bash > /etc/bash_completion.d/oc_completion"
  when: not openshift_client.stat.exists

- name: OC link
  file:
    src: "/opt/oc-{{ oc.version }}/oc"
    dest: "/usr/bin/oc"
    state: link
