---
- name: OS distribution specific vars
  include_vars: "{{ ansible_distribution }}{{ ansible_distribution_version }}.yaml"

- name: OS distribution specific logic
  include_tasks: "{{ ansible_distribution }}{{ ansible_distribution_version }}.yaml"

