---
gpg:
  scdaemon_conf_file: "/home/{{ machine_user }}/.gnupg/scdaemon.conf"
  agent_conf_file: "/home/{{ machine_user }}/.gnupg/gpg-agent.conf"
  conf_file: "/home/{{ machine_user }}/.gnupg/gpg.conf"
  pub_keys:
  # http://keys.gnupg.net/pks/lookup?search=fishi0x01%40gmail.com&fingerprint=on&op=index
  - trusted_key_long_id: "91F47B8CE96231C3"
    ssh_pub_file: "fishi0x01-ssh.pub"
    ssh_pub_dest: "/home/{{ machine_user }}/.ssh/fishi0x01-ssh.pub"

  # RedHat
  - trusted_key_long_id: "9DCDA87BE12A814D"
    ssh_pub_file: "redhat-ssh.pub"
    ssh_pub_dest: "/home/{{ machine_user }}/.ssh/redhat-ssh.pub"
