---
###########
# Alacritty
###########
- name: Get alacritty deb
  get_url:
    url: https://github.com/alacritty/alacritty/releases/download/v0.4.1/Alacritty-v0.4.1-ubuntu_18_04_amd64.deb
    dest: /tmp/alacritty.deb
    checksum: sha256:cb8320d3f5c75349bf6197a6c24a2ee35701d4e06d34515972414f065526557e

- name: Install alacritty
  apt:
    deb: /tmp/alacritty.deb

- name: Set alacritty.desktop
  copy:
    src: files/alacritty.desktop
    dest: "/home/{{ machine_user }}/Desktop/alacritty.desktop"
    owner: "{{ machine_user }}"
    group: "{{ machine_user }}"
    mode: '0755'

# Install fishshell
- name: Add fishshell PPA
  apt_repository:
    repo: ppa:fish-shell/release-3

- name: Install fishshell
  apt:
    name: "fish"
    force_apt_get: yes
    state: present
    update_cache: yes

# Starship
- name: Link starship.toml
  become: yes
  become_user: "{{ machine_user }}"
  file:
    path: "/home/{{ machine_user }}/.config/starship.toml"
    src: "/home/{{ machine_user }}/.starship.toml"
    state: link

# Set bash
- name: Set bash as default shell
  user:
    name: "{{ machine_user }}"
    shell: /bin/bash

# Set permissions for bandwhich
# https://github.com/imsnif/bandwhich#usage
- name: Set permissions for bandwhich
  shell:
    cmd: "setcap cap_sys_ptrace,cap_dac_read_search,cap_net_raw,cap_net_admin+ep /home/{{ machine_user }}/.cargo/bin/bandwhich"
