---
- name: Check if Android Studio is installed
  stat:
    path: "/opt/android-studio-{{ android_studio.version }}"
  register: android_studio_stats

- name: Download and install Android Studio
  block:
    - name: Download Android Studio
      get_url:
        url: "{{ android_studio.url }}"
        dest: "/tmp/android-studio-{{ android_studio.version }}.tar.xz"
        checksum: "{{ android_studio.checksum }}"
        mode: '0777'

    - name: Ensure Arduino Studio dir exists
      file:
        path: "/opt/android-studio-{{ android_studio.version }}"
        state: directory
        mode: '0755'

    - name: Unarchive Android Studio
      unarchive:
        src: "/tmp/android-studio-{{ android_studio.version }}.tar.xz"
        dest: "/opt/android-studio-{{ android_studio.version }}"
        remote_src: true
        extra_opts:
        - "--strip-components=1"

    - name: Set permissions
      file:
        dest: "/opt/android-studio-{{ android_studio.version }}"
        owner: "{{ machine_user }}"
        group: "{{ machine_user }}"
        recurse: true
  when: not android_studio_stats.stat.exists

- name: Android Studio link
  file:
    src: "/opt/android-studio-{{ android_studio.version }}"
    dest: "/opt/android-studio"
    owner: "{{ machine_user }}"
    group: "{{ machine_user }}"
    state: link
