---
- name: Check if PyCharm Community is installed
  stat:
    path: "/opt/pycharm-community-{{ pycharm_community.version }}"
  register: pycharm

- name: Download and install PyCharm Community
  block:
    - name: Download PyCharm Community
      get_url:
        url: "{{ pycharm_community.url }}"
        dest: "/tmp/pycharm-community-{{ pycharm_community.version }}.tar.gz"
        checksum: "{{ pycharm_community.checksum }}"
        mode: '0777'

    - name: Ensure PyCharm Community dir exists
      file:
        path: "/opt/pycharm-community-{{ pycharm_community.version }}"
        state: directory
        mode: '0755'

    - name: Unarchive PyCharm Community
      unarchive:
        src: "/tmp/pycharm-community-{{ pycharm_community.version }}.tar.gz"
        dest: "/opt/pycharm-community-{{ pycharm_community.version }}/"
        remote_src: yes
        extra_opts: "--strip-components=1"
  when: not pycharm.stat.exists

- name: PyCharm Community link
  file:
    src: "/opt/pycharm-community-{{ pycharm_community.version }}"
    dest: "/opt/pycharm-community"
    owner: "{{ machine_user }}"
    group: "{{ machine_user }}"
    state: link
