---
# https://src.fedoraproject.org/rpms/nix
- name: Install nix
  become: true
  ansible.builtin.dnf:
    name: nix-core
    state: present

- name: Make sure nix config dir exists
  ansible.builtin.file:
    path: "/home/{{ machine_user }}/.config/nix"
    owner: "{{ machine_user }}"
    group: "{{ machine_user }}"
    state: directory

- name: Configure nix (enable flakes)
  ansible.builtin.copy:
    content: |
      experimental-features = nix-command flakes
    dest: "/home/{{ machine_user }}/.config/nix/nix.conf"
    owner: "{{ machine_user }}"
    group: "{{ machine_user }}"
