---
- name: distribution specific vars
  include_vars: "{{ ansible_distribution }}{{ ansible_distribution_version }}.yaml"

- name: Add R repo key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ r.apt_key }}"
    state: present

- name: Add R repo
  apt_repository:
    repo: "{{ r.apt_repo }}"
    state: present
    mode: "600"

- name: Install R
  apt:
    name: "{{ r.apt_pkg }}"
    update_cache: yes
    force_apt_get: yes
    state: present
