---
- name: distribution specific vars
  include_vars: "{{ ansible_distribution }}{{ ansible_distribution_version }}.yaml"

- name: "Check if veracrypt is installed"
  package_facts:
    manager: "auto"

- name: Install veracrypt
  block:
    # https://www.idrix.fr/VeraCrypt/VeraCrypt_PGP_public_key.asc
    - name: Copy veracrypt.asc
      copy:
        src: files/veracrypt.asc
        dest: /tmp/veracrypt.asc
        owner: "{{ machine_user }}"
        group: "{{ machine_user }}"
        mode: '0644'

    - name: Import veracrypt.asc
      shell:
        "gpg --import /tmp/veracrypt.asc"

    - name: Download veracrypt.deb
      get_url:
        url: "{{ urls.deb }}"
        dest: /tmp/veracrypt.deb
        mode: '0640'

    - name: Download veracrypt.deb.sig
      get_url:
        url: "{{ urls.sig }}"
        dest: /tmp/veracrypt.deb.sig
        mode: '0440'

    - name: Verify veracrypt signature
      shell:
        "gpg --verify /tmp/veracrypt.deb.sig /tmp/veracrypt.deb"

    - name: Install veracrypt.deb
      apt:
        deb: /tmp/veracrypt.deb
        state: present
        force_apt_get: yes
  when: "'veracrypt-console' not in ansible_facts.packages"
