---
name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    container: fedora:38
    steps:
      - name: Prepare Container
        run: |
          dnf install -y xz util-linux
          useradd fishi0x01
          echo "fishi0x01 ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Tests
        run: |
          su - fishi0x01 && \
          ./scripts/install/install-nix.sh && \
          . /home/fishi0x01/.nix-profile/etc/profile.d/nix.sh && \
          make install-dotfiles && \
          make delete-dotfiles && \
          ./scripts/delete/delete-nix.sh
