---
name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: fedora

    steps:
      - uses: actions/checkout@v2
      - name: '[test] Fedora'
        run: |
          ./scripts/install/install-nix.sh
          make install-dotfiles
          make delete-dotfiles
          ./scripts/delete/delete-nix.sh
